### PR TITLE
Added Instagram like filters for puzzle GSOC-2016

### PR DESCRIPTION
**Pull request by saivig**
Added filters Gotham,Lomo,Kelvin,Sepia

### CODE REVIEW

**Comment by alyosama** [comment]
@saivig you can merge your work with mine to make one plugin with all filters instead of two.

**Comment by saivig** [comment]
@alyosama I think we are being tested for our ability to write new plugins. @diemmarkus are you planning to add instagram like filters as a new plugin?. If so, I will merge my filters into @alyosama's code.

**Comment by diemmarkus** [comment]
hi,
yes, you should not merge your puzzle solutions into one plugin - since we want to see if you can create your own plugin. @saivig - we will give you feedback by tomorrow

**Comment by saivig** [comment]
@diemmarkus please review and merge [#53](https://github.com/nomacs/nomacs/pull/53)
changed a package name typo to ubuntu installation instructions in Readme.md

**Pull request merged**
