### PR TITLE
Add new functions to Paint plugin

### PR DESCRIPTION
**Pull request by sirius1242**
paint3
Features:
- draw line
- draw arrow
- draw circle frame
- draw square frame or filled square
- add blur

Ideas and part of code from [flameshot](https://github.com/lupoDharkael/flameshot/tree/master/src/tools)

### CODE REVIEW

**Comment by sirius1242** [comment]
Sorry, clear() method of QPainterPath was introduced in Qt 5.13, but ubuntu seems don't have release which Qt version >= 5.13

**Comment by sirius1242** [comment]
paint_text
Add function to paint text.

**Comment by diemmarkus** [comment]
pretty impressive, thank you!
-> I'll do some checks and merge it asap

**Comment by diemmarkus** [comment]
thanks a lot!

**Comment by diemmarkus** [comment]
the blur function dramatically slows down rendering if large images are displayed. do you think it's easy to fix that, or should we remove it?

**Comment by sirius1242** [comment]
If only blur function have this problem, I think this maybe because of the use of pixmap, I will try to find whether there is a way to solve it recently.

**Comment by sirius1242** [comment]
#28 did some optimization to blur tool, I'm not certain if this meet your need.

**Pull request merged**
