### PR TITLE
[GSoC 2016] puzzle. Created a filter similar to x-Pro II

### PR DESCRIPTION
**Pull request by praveenagrawal**
Please tell me if it meets the expectations.

### CODE REVIEW

**Comment by diemmarkus** [comment]
Hi,
please remove all autogenerated files from the request...
regards,
Markus

**Comment by praveenagrawal** [comment]
Done. Sorry for that.

**Comment by diemmarkus** [comment]
thanks for submitting your solution - the vignetting works fine, though I am missing a color filter...

**Comment by praveenagrawal** [comment]
I had left out the colour filter because I was not getting a good
approximation of the required transformation functions. I am doing it now.

**Comment by praveenagrawal** [comment]
I have added a colour filter. Please check it.

**Pull request merged**
